name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: yarn

    # - name: Check Links
    #   run: yarn docs:check

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: Functional-Genomics-Lab/Applied-Genomics
        BUILD_SCRIPT: yarn && yarn docs:build
        # The `cd docs` keeps it in the docs directory
        BUILD_DIR: docs/.vuepress/dist/